#!/bin/bash

# basic utility checks
[[ $(type -P http) ]] || { echo "Please install httpie"; exit 1; }
[[ $(type -P curl) ]] || { echo "Please install curl"; exit 1; }

# check if the server is up
if [[ $( curl -s https://threads.iiit.ac.in:5000/test ) != "Success" ]]; then
    echo "The server is not alive"
    exit 1
fi

if (( $# < 2 )); then
    echo "Usage: $0 <start|stat|move r c> PORT"
    exit 1;
fi

MOVE_REGEX='[0-9a-zA-Z]'

while (( $# > 0 )); do
    case "$1" in
        start )
            if (( $# < 6 )); then
                echo "Usage: $0 start PORT team1 team2 ip1 ip2"
                exit 1;
            fi
            PORT="$2"
            PL1="$3"
            PL2="$4"
            IP1="$5"
            IP2="$6"
            # 10.1.135.161
            # 10.1.134.188
            http -f POST https://threads.iiit.ac.in:"$PORT"/game/start p2="$PL2" p1="$PL1" ip1="$IP1" ip2="$IP2" board_size=10
            shift 2 ;;
        move )
            shift

            if (( $# < 3 )); then
                echo "Please supply both row and col for move"
                exit 1
            fi

            R_POS="$1"
            C_POS="$2"
            PORT="$3"

            if ! [[ "$( grep -P "$MOVE_REGEX" <<< "$R_POS" )" || "$( grep -P "$MOVE_REGEX" <<< "$C_POS" )" ]]; then
                echo "Please supply row/col pos in [0-9a-zA-Z]"
                exit 1
            fi

            http -f POST https://threads.iiit.ac.in:"$PORT"/game/make_move r_pos="$R_POS" c_pos="$C_POS"
            shift 3 ;;
        stat )
            PORT="$2"
            http -f GET https://threads.iiit.ac.in:"$PORT"/game/get_status
            shift 2 ;;
    esac
done
